### ISSUE TITLE
Receive Payments

### ISSUE THREAD

**Issue by mahithedula** [CMU-17-356/dronuts-2023-krispykopters#25] opened 2023-01-31 17:01 UTC
Card:  
As a donut shop owner, I want to receive payments from customers, so that I can get paid for my product.

Conversation:
CommerceFried should relay user’s payments for their orders to the donut shop with details of the associated order.

Confirmation:
The donut shop can see the money from an order hit their account after an order is made.

**Comment by JunTaoLuo** [comment] 2023-02-01 23:58
Potential duplicate of https://github.com/CMU-17-356/dronuts-2023-krispykopters/issues/4

**Comment by Bwillia2** [comment] 2023-02-02 17:48
agreed, same as #4

**Closed by Bwillia2** 2023-02-02 17:48 UTC
Labels: Large
