### ISSUE TITLE
Show Item Stock

### ISSUE THREAD

**Issue by OpheliaLjh** [CMU-17-356/dronuts-2023-krispykopters#12] opened 2023-01-31 16:46 UTC
## Card
As a customer, I want to be able to view and buy all the in-stock donuts online offered by the donut shop, so that it saves me time from calling the store or going to the store

## Conversation
add shopping cart, checkout, show all the donut options
+The donut shop’s donut menu should have real-time access to the donut shop’s inventory.

## Confirmation
the website is stable, the shopping failure rate is low, few complaints

**Comment by JunTaoLuo** [comment] 2023-02-01 23:58
Potential duplicate of https://github.com/CMU-17-356/dronuts-2023-krispykopters/issues/23

**Closed** 2023-02-28 16:16 UTC
Labels: Small
